/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TestJniPrimitive */

#ifndef _Included_TestJniPrimitive
#define _Included_TestJniPrimitive
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TestJniPrimitive
 * Method:    average
 * Signature: (II)D
 */
JNIEXPORT jdouble JNICALL Java_TestJniPrimitive_average
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
