/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class HelloJniCpp */

#ifndef _Included_HelloJniCpp
#define _Included_HelloJniCpp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     HelloJniCpp
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_HelloJniCpp_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
