/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class myjni_HelloJni */

#ifndef _Included_myjni_HelloJni
#define _Included_myjni_HelloJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     myjni_HelloJni
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_myjni_HelloJni_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
